#!/usr/bin/env bash

# Generate the CPP header file with all Avro specific record.
#
# This requires the Avro dependency to have been built first (for example using
# the `build-deps` script).

set -o nounset
set -o errexit
set -o pipefail
shopt -s nullglob

# `etc/` directory.
dpath="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"${dpath}/deps/avro/lang/c++/build/avrogencpp" \
  -i <("${dpath}/scripts/assemble-idls") \
  -o "${dpath}/../src/pdus.hpp" \
  -n Layer2
