#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
shopt -s nullglob

# `etc/` directory.
dpath="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"${dpath}/deps/avro/lang/c++/build/avrogencpp" \
  -i <("${dpath}/scripts/assemble-idls") \
  -o "${dpath}/../src/pdus.hpp" \
  -n Layer2;
